#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Dec  3 16:00:45 2021

@author: albert
"""
import numpy as np
import matplotlib.pyplot as plt
simdays = 21
beta = 0.4
gamma = 1/3


def mpfun(t,beta,gamma,simdays):
    if type(t) is int:
        return [0.05*np.sin(2*np.pi/simdays*t)+beta,gamma]
    else:
        return np.vstack([0.05*np.sin(2*np.pi/simdays*t)+beta,gamma*np.ones(len(t))]).T
        #return np.vstack([beta*np.ones(len(t)),gamma*np.ones(len(t))]).T
    
mp_actual = mpfun(np.arange(t_0,day, dt), beta, gamma, simdays)   
dt = 0.1

for day in range(1,simdays):
    days_for_est = 4
    if days_for_est > day:
        days_for_est = day
    t_0 = day-days_for_est
    
    
    t_train = np.arange(t_0,day, dt)
    mp_day = mpfun(t_train+day-1, beta, gamma, simdays)
    plt.plot(t_train,mp_day)
    if day == 1:
        beta_mp = list(mp_day[:,0])
        gamma_mp = list(mp_day[:,1])
    else:
        beta_mp += list(mp_day[:,0])
        gamma_mp += list(mp_day[:,1])
    
    